### ISSUE TITLE
Convert to HQ some part of celeba dataset

### ISSUE THREAD

**Issue by abi98213** [nperraud/download-celebA-HQ#11]
I want the celeba hq dataset for some task in which I just want 2000 images.
So I have downloaded the celeba dataset, but please tell me which delta should I download ( Because I have slow internet connection ) to convert it to HQ, and what will be the process

**Comment by nperraud** [comment]
I am sorry. I wrote the code a long time ago and I do not really remember it. So I cannot help you.
Good luck

**Comment by abi98213** [comment]
No problem, Thanks
