### ISSUE TITLE
celebA-HQ output is 3*3 image replication with 1024*1024?

### ISSUE THREAD

**Issue by HavenFeng** [nperraud/download-celebA-HQ#8]
Hi nperraud,
Thanks for your code, I'm running the make_HQ_images.py without any problem, but the result is not a single subject 1024by1024 image but a 3by3 replication of the subject(and the image is in grey scale).
Is this normal or I missed some steps?  Here is an example:
![celebhq_test](https://user-images.githubusercontent.com/16853754/47158740-92b12d80-d2ec-11e8-86af-2bf66737408d.png)

**Comment by HavenFeng** [comment]
Oh, I just found it's a numpy reshape problem. The code runs very well.

**Comment by vjtrost88** [comment]
@HavenFeng I'm having the same problem here - what was your reshaping solution?

**Comment by vjtrost88** [comment]
Figured it out. For anyone else who might be encountering this problem, use the following:
`img = img.transpose(0,2,3,1)` where `img` is the numpy array for the image. Just need to reorder things, so image stays first, height second, width third, and channels fourth.

**Comment by nperraud** [comment]
So should I change something in my code?

**Comment by vjtrost88** [comment]
@nperraud I don't think so - unless you want your code to save image files too. The code does a great job of reconstructing the `.npy` files. Images are icing on the cake. Thanks for this repo, it worked great and helped a ton!

**Comment by nperraud** [comment]
Happy that you found it useful! 
Thanks for your clear answer.
